### ISSUE TITLE
@JaegerCodes Sometime blob file download but its not able to open

### ISSUE THREAD

**Issue by AmitSonake** [JaegerCodes/AmazingAndroidWebview#1]
Hi There,

I tried your code to download blob file from web view  and its working but I found one observation like some time blob file able to download but its not able to open and some time its download and able to open the file. what's the issue i am unable to find the solution could you please help me out here. thanks.

**Comment by JaegerCodes** [comment]
This is only an example to demostrate how to execute JS code in a webview. Best
